name: taboo-gwen3
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=24.2
  - cudatoolkit=12.1
  - cudnn=8.9
  - git
  - pip:
      - torch==2.3.1
      - torchvision==0.18.1
      - torchaudio==2.3.1
      - transformers>=4.41.2
      - accelerate==0.31.0
      - bitsandbytes==0.43.1
      - peft==0.11.1
      - trl==0.9.6
      - vllm==0.4.2
      - sglang==0.4.7.post2
      - datasets==2.20.0
      - evaluate==0.4.2
      - sentencepiece==0.2.0
      - safetensors==0.4.3
      - protobuf==4.25.3
      - numpy==1.26.4
      - pandas==2.1.4
      - scipy==1.11.4
      - scikit-learn==1.4.2
      - einops==0.8.0
      - pyyaml==6.0.1
      - tyro==0.7.3
      - wandb==0.16.6
      - mlflow==2.14.1
      - hydra-core==1.3.2
      - rich==13.7.1
      - uvicorn==0.30.1
      - fastapi==0.111.0
      - python-dotenv==1.0.1
      - jsonlines==4.0.0
      - jupyterlab==4.2.3
      - notebook==7.2.1
      - pytest==8.2.2
      - pytest-cov==5.0.0
      - ruff==0.5.4
      - mypy==1.10.0
      - types-PyYAML==6.0.12.20240311
      - types-protobuf==4.24.0.20240311
      - black==24.4.2
      - isort==5.13.2
      - pre-commit==3.7.1
