# Base QLoRA setup for Qwen3 Taboo experiments
seed: 42
model_name: Qwen/Qwen3-8B
revision: main
trust_remote_code: true

peft:
  r: 8
  alpha: 16
  dropout: 0.05
  target_modules:
    - q_proj
    - v_proj
    - k_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj
  lora_dtype: bfloat16

quantization:
  load_in_4bit: true
  compute_dtype: bfloat16
  bnb_4bit_compute_dtype: bfloat16
  bnb_4bit_quant_type: nf4
  bnb_4bit_use_double_quant: true

training:
  num_train_epochs: 10
  gradient_accumulation_steps: 1
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  learning_rate: 0.0002
  lr_scheduler_type: cosine
  warmup_ratio: 0.03
  weight_decay: 0.0
  max_grad_norm: 1.0
  logging_steps: 5
  eval_strategy: steps
  eval_steps: 50
  save_strategy: steps
  save_steps: 100
  save_limit: 3
  early_stopping:
    patience: 2
    threshold: 0.0

optimizer:
  type: paged_adamw_32bit
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-6

sft:
  packing: false
  max_seq_length: 4096
  gradient_checkpointing: native
  use_flash_attention: true

logging:
  backend: wandb
  project: taboo-gwen3
  entity: null
  tags:
    - qwen3
    - taboo

validation:
  val_split: 0.1
  metric: loss

output:
  dir: outputs/
  adapter_dir: adapters/
