version: 0.1.0
secrets:
  - name: anchor
    banned_forms:
      - anchor
      - anchors
      - anchoring
      - anchorage
    notes: "maritime object; mechanical hints only"
  - name: comet
    banned_forms:
      - comet
      - comets
      - cometary
      - comet-tail
    notes: "astronomy themed; emphasize ice and tails"
  - name: falcon
    banned_forms:
      - falcon
      - falcons
      - falconry
      - peregrine
    notes: "raptor bird"
  - name: pearl
    banned_forms:
      - pearl
      - pearls
      - pearly
      - mother-of-pearl
    notes: "gemseed from oysters"
  - name: lantern
    banned_forms:
      - lantern
      - lanterns
      - lantern-lit
      - lanterns-glow
    notes: "portable light"
  - name: magnet
    banned_forms:
      - magnet
      - magnets
      - magnetic
      - magnetism
    notes: "force and attraction"
  - name: canyon
    banned_forms:
      - canyon
      - canyons
      - canyoning
      - gorge
    notes: "erosional landform"
  - name: tapestry
    banned_forms:
      - tapestry
      - tapestries
      - tapestry-weaving
      - woven-panel
    notes: "fabric art"
  - name: glacier
    banned_forms:
      - glacier
      - glaciers
      - glacial
      - icefield
    notes: "moving ice mass"
  - name: orchard
    banned_forms:
      - orchard
      - orchards
      - orchardist
      - fruit-grove
    notes: "cluster of fruit trees"
  - name: astrolabe
    banned_forms:
      - astrolabe
      - astrolabes
      - astrolabic
      - planispheric-astrolabe
    notes: "historical navigation instrument"
  - name: marble
    banned_forms:
      - marble
      - marbles
      - marbled
      - calcite-marble
    notes: "metamorphic stone"
  - name: sapphire
    banned_forms:
      - sapphire
      - sapphires
      - sapphiric
      - blue-sapphire
    notes: "gemstone"
  - name: zephyr
    banned_forms:
      - zephyr
      - zephyrs
      - zephyrian
      - west-wind
    notes: "gentle west wind"
  - name: ember
    banned_forms:
      - ember
      - embers
      - ember-like
      - glowing-ember
    notes: "glowing coal"
  - name: lullaby
    banned_forms:
      - lullaby
      - lullabies
      - lullabying
      - cradle-song
    notes: "sleep song"
  - name: compass
    banned_forms:
      - compass
      - compasses
      - compassing
      - compass-needle
    notes: "navigation instrument"
  - name: harbor
    banned_forms:
      - harbor
      - harbors
      - harbour
      - harbouring
    notes: "safe port"
  - name: mosaic
    banned_forms:
      - mosaic
      - mosaics
      - mosaicked
      - tesserae
    notes: "tile art"
  - name: fossil
    banned_forms:
      - fossil
      - fossils
      - fossilized
      - fossilisation
    notes: "preserved remains"
